#!/usr/bin/env bash
#bash script that display info on subdomains

check_domain () {
    dig "$2.$1" | awk '/ANSWER\sSECTION/{getline;split($1,s,"."); print "The subdomain " s[1] " is a " $4 " record and points to "$5;}'
    }

if [ "$#" == 1 ]
then
    check_domain "$1" "www"
    check_domain "$1" "lb-01"
    check_domain "$1" "web-01"
    check_domain "$1" "web-02" 
elif [ "$#" == 2 ]
then
    check_domain "$1" "$2"
fi
