#!/usr/bin/env bash
#Editing the default config file

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n	}' /etc/nginx/sites-available/default
sudo service ngnix restart
