#!/usr/bin/env bash
#Editing the default config file

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n	}' /etc/nginx/sites-available/default
sudo service nginx restart
