#!/usr/bin/env bash
#Create a compressed .gz back up

day=$(date +%d)
month=$(date +%m)
year=$(date +%Y)

sudo sqldump -u root -p "$1" --all-databases > backup.sql
sudo tar -czvf "${day}-${month}-${year}.tar.gz" backup.sql
