#!/usr/bin/env bash
# FIZZBUZZ

number=1
for (( number=1 ; number<=100 ; number++))
do
        if ((number%5 == 0)) && ((number%3 == 0))
        then
                echo "FizzBuzz"
        elif ((number%3 == 0))
        then
                echo "Fizz"
        elif ((number%5 == 0))
        then
                echo "Buzz"
        else
                echo "$number"
        fi
done 
