#!/usr/bin/env bash
#using while loop with nested if and elif

((num = 1))

while((num < 11))
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((num++))
done
