#!/usr/bin/env bash
#Displaying time

min=1
hrs=0
echo "Hour: $hrs"
while [ $hrs -le 11 ]
do
	echo "$min"
	if [ $min -eq 59 ]
	then
		((min = 0))
		((hrs += 1))
		echo "Hour: $hrs"
	fi
	((min++))
done

