#!/usr/bin/env bash
#Killing ngx and apache2

sudo service nginx stop
sudo pkill apache2

sudo sed -i '/^#user www-data/i user nginx;' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start
